package model.tuanmei_operation.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class jumei_mall_draftExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public jumei_mall_draftExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_mall_draftExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_mall_draftExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        jumei_mall_draftExample example = new jumei_mall_draftExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_mall_draftExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_mall_draftExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMallIdIsNull() {
            addCriterion("mall_id is null");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNotNull() {
            addCriterion("mall_id is not null");
            return (Criteria) this;
        }

        public Criteria andMallIdEqualTo(Integer value) {
            addCriterion("mall_id =", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotEqualTo(Integer value) {
            addCriterion("mall_id <>", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThan(Integer value) {
            addCriterion("mall_id >", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mall_id >=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThan(Integer value) {
            addCriterion("mall_id <", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThanOrEqualTo(Integer value) {
            addCriterion("mall_id <=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdIn(List<Integer> values) {
            addCriterion("mall_id in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotIn(List<Integer> values) {
            addCriterion("mall_id not in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdBetween(Integer value1, Integer value2) {
            addCriterion("mall_id between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mall_id not between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdIsNull() {
            addCriterion("sale_type_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdIsNotNull() {
            addCriterion("sale_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdEqualTo(Integer value) {
            addCriterion("sale_type_id =", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdNotEqualTo(Integer value) {
            addCriterion("sale_type_id <>", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdGreaterThan(Integer value) {
            addCriterion("sale_type_id >", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_type_id >=", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdLessThan(Integer value) {
            addCriterion("sale_type_id <", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("sale_type_id <=", value, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdIn(List<Integer> values) {
            addCriterion("sale_type_id in", values, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdNotIn(List<Integer> values) {
            addCriterion("sale_type_id not in", values, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("sale_type_id between", value1, value2, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andSaleTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_type_id not between", value1, value2, "saleTypeId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdIsNull() {
            addCriterion("shipping_system_id is null");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdIsNotNull() {
            addCriterion("shipping_system_id is not null");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdEqualTo(Integer value) {
            addCriterion("shipping_system_id =", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdNotEqualTo(Integer value) {
            addCriterion("shipping_system_id <>", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdGreaterThan(Integer value) {
            addCriterion("shipping_system_id >", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shipping_system_id >=", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdLessThan(Integer value) {
            addCriterion("shipping_system_id <", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdLessThanOrEqualTo(Integer value) {
            addCriterion("shipping_system_id <=", value, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdIn(List<Integer> values) {
            addCriterion("shipping_system_id in", values, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdNotIn(List<Integer> values) {
            addCriterion("shipping_system_id not in", values, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdBetween(Integer value1, Integer value2) {
            addCriterion("shipping_system_id between", value1, value2, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andShippingSystemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shipping_system_id not between", value1, value2, "shippingSystemId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceIsNull() {
            addCriterion("sku_min_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceIsNotNull() {
            addCriterion("sku_min_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceEqualTo(BigDecimal value) {
            addCriterion("sku_min_price =", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceNotEqualTo(BigDecimal value) {
            addCriterion("sku_min_price <>", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceGreaterThan(BigDecimal value) {
            addCriterion("sku_min_price >", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_min_price >=", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceLessThan(BigDecimal value) {
            addCriterion("sku_min_price <", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_min_price <=", value, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceIn(List<BigDecimal> values) {
            addCriterion("sku_min_price in", values, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceNotIn(List<BigDecimal> values) {
            addCriterion("sku_min_price not in", values, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_min_price between", value1, value2, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMinPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_min_price not between", value1, value2, "skuMinPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceIsNull() {
            addCriterion("sku_max_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceIsNotNull() {
            addCriterion("sku_max_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceEqualTo(BigDecimal value) {
            addCriterion("sku_max_price =", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceNotEqualTo(BigDecimal value) {
            addCriterion("sku_max_price <>", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceGreaterThan(BigDecimal value) {
            addCriterion("sku_max_price >", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_max_price >=", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceLessThan(BigDecimal value) {
            addCriterion("sku_max_price <", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_max_price <=", value, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceIn(List<BigDecimal> values) {
            addCriterion("sku_max_price in", values, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceNotIn(List<BigDecimal> values) {
            addCriterion("sku_max_price not in", values, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_max_price between", value1, value2, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_max_price not between", value1, value2, "skuMaxPrice");
            return (Criteria) this;
        }

        public Criteria andMinDiscountIsNull() {
            addCriterion("min_discount is null");
            return (Criteria) this;
        }

        public Criteria andMinDiscountIsNotNull() {
            addCriterion("min_discount is not null");
            return (Criteria) this;
        }

        public Criteria andMinDiscountEqualTo(BigDecimal value) {
            addCriterion("min_discount =", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountNotEqualTo(BigDecimal value) {
            addCriterion("min_discount <>", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountGreaterThan(BigDecimal value) {
            addCriterion("min_discount >", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("min_discount >=", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountLessThan(BigDecimal value) {
            addCriterion("min_discount <", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("min_discount <=", value, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountIn(List<BigDecimal> values) {
            addCriterion("min_discount in", values, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountNotIn(List<BigDecimal> values) {
            addCriterion("min_discount not in", values, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_discount between", value1, value2, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andMinDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_discount not between", value1, value2, "minDiscount");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceIsNull() {
            addCriterion("sku_max_market_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceIsNotNull() {
            addCriterion("sku_max_market_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceEqualTo(BigDecimal value) {
            addCriterion("sku_max_market_price =", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceNotEqualTo(BigDecimal value) {
            addCriterion("sku_max_market_price <>", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceGreaterThan(BigDecimal value) {
            addCriterion("sku_max_market_price >", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_max_market_price >=", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceLessThan(BigDecimal value) {
            addCriterion("sku_max_market_price <", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sku_max_market_price <=", value, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceIn(List<BigDecimal> values) {
            addCriterion("sku_max_market_price in", values, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceNotIn(List<BigDecimal> values) {
            addCriterion("sku_max_market_price not in", values, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_max_market_price between", value1, value2, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMaxMarketPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sku_max_market_price not between", value1, value2, "skuMaxMarketPrice");
            return (Criteria) this;
        }

        public Criteria andProductShortNameIsNull() {
            addCriterion("product_short_name is null");
            return (Criteria) this;
        }

        public Criteria andProductShortNameIsNotNull() {
            addCriterion("product_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductShortNameEqualTo(String value) {
            addCriterion("product_short_name =", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameNotEqualTo(String value) {
            addCriterion("product_short_name <>", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameGreaterThan(String value) {
            addCriterion("product_short_name >", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_short_name >=", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameLessThan(String value) {
            addCriterion("product_short_name <", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameLessThanOrEqualTo(String value) {
            addCriterion("product_short_name <=", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameLike(String value) {
            addCriterion("product_short_name like", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameNotLike(String value) {
            addCriterion("product_short_name not like", value, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameIn(List<String> values) {
            addCriterion("product_short_name in", values, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameNotIn(List<String> values) {
            addCriterion("product_short_name not in", values, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameBetween(String value1, String value2) {
            addCriterion("product_short_name between", value1, value2, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductShortNameNotBetween(String value1, String value2) {
            addCriterion("product_short_name not between", value1, value2, "productShortName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameIsNull() {
            addCriterion("product_medium_name is null");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameIsNotNull() {
            addCriterion("product_medium_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameEqualTo(String value) {
            addCriterion("product_medium_name =", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameNotEqualTo(String value) {
            addCriterion("product_medium_name <>", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameGreaterThan(String value) {
            addCriterion("product_medium_name >", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_medium_name >=", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameLessThan(String value) {
            addCriterion("product_medium_name <", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameLessThanOrEqualTo(String value) {
            addCriterion("product_medium_name <=", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameLike(String value) {
            addCriterion("product_medium_name like", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameNotLike(String value) {
            addCriterion("product_medium_name not like", value, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameIn(List<String> values) {
            addCriterion("product_medium_name in", values, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameNotIn(List<String> values) {
            addCriterion("product_medium_name not in", values, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameBetween(String value1, String value2) {
            addCriterion("product_medium_name between", value1, value2, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductMediumNameNotBetween(String value1, String value2) {
            addCriterion("product_medium_name not between", value1, value2, "productMediumName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameIsNull() {
            addCriterion("product_long_name is null");
            return (Criteria) this;
        }

        public Criteria andProductLongNameIsNotNull() {
            addCriterion("product_long_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductLongNameEqualTo(String value) {
            addCriterion("product_long_name =", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameNotEqualTo(String value) {
            addCriterion("product_long_name <>", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameGreaterThan(String value) {
            addCriterion("product_long_name >", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_long_name >=", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameLessThan(String value) {
            addCriterion("product_long_name <", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameLessThanOrEqualTo(String value) {
            addCriterion("product_long_name <=", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameLike(String value) {
            addCriterion("product_long_name like", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameNotLike(String value) {
            addCriterion("product_long_name not like", value, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameIn(List<String> values) {
            addCriterion("product_long_name in", values, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameNotIn(List<String> values) {
            addCriterion("product_long_name not in", values, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameBetween(String value1, String value2) {
            addCriterion("product_long_name between", value1, value2, "productLongName");
            return (Criteria) this;
        }

        public Criteria andProductLongNameNotBetween(String value1, String value2) {
            addCriterion("product_long_name not between", value1, value2, "productLongName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Integer value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Integer value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Integer value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Integer value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Integer value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Integer> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Integer> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private jumei_mall_draftExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(jumei_mall_draftExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public jumei_mall_draftExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table jumei_mall_draft
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void criteria(Criteria criteria);
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_mall_draft
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void example(model.tuanmei_operation.pojo.jumei_mall_draftExample example);
    }
}