package model.tuanmei_operation.pojo;

public class jumei_deals_plugin {
    private String hashId;

    private String site;

    private Boolean isPublishedPrice;

    private Boolean isWishToBuy;

    private Boolean isPublishedShowStocks;

    private Integer showStocks;

    private String wishTitle;

    private Integer wishNumber;

    private Integer realWishNumber;

    private Boolean isStockSplit;

    private Boolean usingTitle;

    private Integer sort;

    public jumei_deals_plugin(String hashId, String site, Boolean isPublishedPrice, Boolean isWishToBuy, Boolean isPublishedShowStocks, Integer showStocks, String wishTitle, Integer wishNumber, Integer realWishNumber, Boolean isStockSplit, Boolean usingTitle, Integer sort) {
        this.hashId = hashId;
        this.site = site;
        this.isPublishedPrice = isPublishedPrice;
        this.isWishToBuy = isWishToBuy;
        this.isPublishedShowStocks = isPublishedShowStocks;
        this.showStocks = showStocks;
        this.wishTitle = wishTitle;
        this.wishNumber = wishNumber;
        this.realWishNumber = realWishNumber;
        this.isStockSplit = isStockSplit;
        this.usingTitle = usingTitle;
        this.sort = sort;
    }

    public jumei_deals_plugin() {
        super();
    }

    public String getHashId() {
        return hashId;
    }

    public void setHashId(String hashId) {
        this.hashId = hashId == null ? null : hashId.trim();
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    public Boolean getIsPublishedPrice() {
        return isPublishedPrice;
    }

    public void setIsPublishedPrice(Boolean isPublishedPrice) {
        this.isPublishedPrice = isPublishedPrice;
    }

    public Boolean getIsWishToBuy() {
        return isWishToBuy;
    }

    public void setIsWishToBuy(Boolean isWishToBuy) {
        this.isWishToBuy = isWishToBuy;
    }

    public Boolean getIsPublishedShowStocks() {
        return isPublishedShowStocks;
    }

    public void setIsPublishedShowStocks(Boolean isPublishedShowStocks) {
        this.isPublishedShowStocks = isPublishedShowStocks;
    }

    public Integer getShowStocks() {
        return showStocks;
    }

    public void setShowStocks(Integer showStocks) {
        this.showStocks = showStocks;
    }

    public String getWishTitle() {
        return wishTitle;
    }

    public void setWishTitle(String wishTitle) {
        this.wishTitle = wishTitle == null ? null : wishTitle.trim();
    }

    public Integer getWishNumber() {
        return wishNumber;
    }

    public void setWishNumber(Integer wishNumber) {
        this.wishNumber = wishNumber;
    }

    public Integer getRealWishNumber() {
        return realWishNumber;
    }

    public void setRealWishNumber(Integer realWishNumber) {
        this.realWishNumber = realWishNumber;
    }

    public Boolean getIsStockSplit() {
        return isStockSplit;
    }

    public void setIsStockSplit(Boolean isStockSplit) {
        this.isStockSplit = isStockSplit;
    }

    public Boolean getUsingTitle() {
        return usingTitle;
    }

    public void setUsingTitle(Boolean usingTitle) {
        this.usingTitle = usingTitle;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static jumei_deals_plugin.Builder builder() {
        return new jumei_deals_plugin.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private jumei_deals_plugin obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new jumei_deals_plugin();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.hash_id
         *
         * @param hashId the value for jumei_deals_plugin.hash_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder hashId(String hashId) {
            obj.setHashId(hashId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.site
         *
         * @param site the value for jumei_deals_plugin.site
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder site(String site) {
            obj.setSite(site);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.is_published_price
         *
         * @param isPublishedPrice the value for jumei_deals_plugin.is_published_price
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isPublishedPrice(Boolean isPublishedPrice) {
            obj.setIsPublishedPrice(isPublishedPrice);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.is_wish_to_buy
         *
         * @param isWishToBuy the value for jumei_deals_plugin.is_wish_to_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isWishToBuy(Boolean isWishToBuy) {
            obj.setIsWishToBuy(isWishToBuy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.is_published_show_stocks
         *
         * @param isPublishedShowStocks the value for jumei_deals_plugin.is_published_show_stocks
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isPublishedShowStocks(Boolean isPublishedShowStocks) {
            obj.setIsPublishedShowStocks(isPublishedShowStocks);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.show_stocks
         *
         * @param showStocks the value for jumei_deals_plugin.show_stocks
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder showStocks(Integer showStocks) {
            obj.setShowStocks(showStocks);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.wish_title
         *
         * @param wishTitle the value for jumei_deals_plugin.wish_title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder wishTitle(String wishTitle) {
            obj.setWishTitle(wishTitle);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.wish_number
         *
         * @param wishNumber the value for jumei_deals_plugin.wish_number
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder wishNumber(Integer wishNumber) {
            obj.setWishNumber(wishNumber);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.real_wish_number
         *
         * @param realWishNumber the value for jumei_deals_plugin.real_wish_number
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder realWishNumber(Integer realWishNumber) {
            obj.setRealWishNumber(realWishNumber);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.is_stock_split
         *
         * @param isStockSplit the value for jumei_deals_plugin.is_stock_split
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isStockSplit(Boolean isStockSplit) {
            obj.setIsStockSplit(isStockSplit);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.using_title
         *
         * @param usingTitle the value for jumei_deals_plugin.using_title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder usingTitle(Boolean usingTitle) {
            obj.setUsingTitle(usingTitle);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_deals_plugin.sort
         *
         * @param sort the value for jumei_deals_plugin.sort
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder sort(Integer sort) {
            obj.setSort(sort);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public jumei_deals_plugin build() {
            return this.obj;
        }
    }
}