package model.tuanmei_operation.pojo;

import java.util.ArrayList;
import java.util.List;

public class jumei_deals_pluginExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public jumei_deals_pluginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_deals_pluginExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_deals_pluginExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        jumei_deals_pluginExample example = new jumei_deals_pluginExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_deals_pluginExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public jumei_deals_pluginExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHashIdIsNull() {
            addCriterion("hash_id is null");
            return (Criteria) this;
        }

        public Criteria andHashIdIsNotNull() {
            addCriterion("hash_id is not null");
            return (Criteria) this;
        }

        public Criteria andHashIdEqualTo(String value) {
            addCriterion("hash_id =", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdNotEqualTo(String value) {
            addCriterion("hash_id <>", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdGreaterThan(String value) {
            addCriterion("hash_id >", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdGreaterThanOrEqualTo(String value) {
            addCriterion("hash_id >=", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdLessThan(String value) {
            addCriterion("hash_id <", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdLessThanOrEqualTo(String value) {
            addCriterion("hash_id <=", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdLike(String value) {
            addCriterion("hash_id like", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdNotLike(String value) {
            addCriterion("hash_id not like", value, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdIn(List<String> values) {
            addCriterion("hash_id in", values, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdNotIn(List<String> values) {
            addCriterion("hash_id not in", values, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdBetween(String value1, String value2) {
            addCriterion("hash_id between", value1, value2, "hashId");
            return (Criteria) this;
        }

        public Criteria andHashIdNotBetween(String value1, String value2) {
            addCriterion("hash_id not between", value1, value2, "hashId");
            return (Criteria) this;
        }

        public Criteria andSiteIsNull() {
            addCriterion("site is null");
            return (Criteria) this;
        }

        public Criteria andSiteIsNotNull() {
            addCriterion("site is not null");
            return (Criteria) this;
        }

        public Criteria andSiteEqualTo(String value) {
            addCriterion("site =", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotEqualTo(String value) {
            addCriterion("site <>", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThan(String value) {
            addCriterion("site >", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThanOrEqualTo(String value) {
            addCriterion("site >=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThan(String value) {
            addCriterion("site <", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThanOrEqualTo(String value) {
            addCriterion("site <=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLike(String value) {
            addCriterion("site like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotLike(String value) {
            addCriterion("site not like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteIn(List<String> values) {
            addCriterion("site in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotIn(List<String> values) {
            addCriterion("site not in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteBetween(String value1, String value2) {
            addCriterion("site between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotBetween(String value1, String value2) {
            addCriterion("site not between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceIsNull() {
            addCriterion("is_published_price is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceIsNotNull() {
            addCriterion("is_published_price is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceEqualTo(Boolean value) {
            addCriterion("is_published_price =", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceNotEqualTo(Boolean value) {
            addCriterion("is_published_price <>", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceGreaterThan(Boolean value) {
            addCriterion("is_published_price >", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_published_price >=", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceLessThan(Boolean value) {
            addCriterion("is_published_price <", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceLessThanOrEqualTo(Boolean value) {
            addCriterion("is_published_price <=", value, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceIn(List<Boolean> values) {
            addCriterion("is_published_price in", values, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceNotIn(List<Boolean> values) {
            addCriterion("is_published_price not in", values, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published_price between", value1, value2, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsPublishedPriceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published_price not between", value1, value2, "isPublishedPrice");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyIsNull() {
            addCriterion("is_wish_to_buy is null");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyIsNotNull() {
            addCriterion("is_wish_to_buy is not null");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyEqualTo(Boolean value) {
            addCriterion("is_wish_to_buy =", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyNotEqualTo(Boolean value) {
            addCriterion("is_wish_to_buy <>", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyGreaterThan(Boolean value) {
            addCriterion("is_wish_to_buy >", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_wish_to_buy >=", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyLessThan(Boolean value) {
            addCriterion("is_wish_to_buy <", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyLessThanOrEqualTo(Boolean value) {
            addCriterion("is_wish_to_buy <=", value, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyIn(List<Boolean> values) {
            addCriterion("is_wish_to_buy in", values, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyNotIn(List<Boolean> values) {
            addCriterion("is_wish_to_buy not in", values, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyBetween(Boolean value1, Boolean value2) {
            addCriterion("is_wish_to_buy between", value1, value2, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsWishToBuyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_wish_to_buy not between", value1, value2, "isWishToBuy");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksIsNull() {
            addCriterion("is_published_show_stocks is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksIsNotNull() {
            addCriterion("is_published_show_stocks is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksEqualTo(Boolean value) {
            addCriterion("is_published_show_stocks =", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksNotEqualTo(Boolean value) {
            addCriterion("is_published_show_stocks <>", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksGreaterThan(Boolean value) {
            addCriterion("is_published_show_stocks >", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_published_show_stocks >=", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksLessThan(Boolean value) {
            addCriterion("is_published_show_stocks <", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksLessThanOrEqualTo(Boolean value) {
            addCriterion("is_published_show_stocks <=", value, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksIn(List<Boolean> values) {
            addCriterion("is_published_show_stocks in", values, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksNotIn(List<Boolean> values) {
            addCriterion("is_published_show_stocks not in", values, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published_show_stocks between", value1, value2, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andIsPublishedShowStocksNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published_show_stocks not between", value1, value2, "isPublishedShowStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksIsNull() {
            addCriterion("show_stocks is null");
            return (Criteria) this;
        }

        public Criteria andShowStocksIsNotNull() {
            addCriterion("show_stocks is not null");
            return (Criteria) this;
        }

        public Criteria andShowStocksEqualTo(Integer value) {
            addCriterion("show_stocks =", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksNotEqualTo(Integer value) {
            addCriterion("show_stocks <>", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksGreaterThan(Integer value) {
            addCriterion("show_stocks >", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_stocks >=", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksLessThan(Integer value) {
            addCriterion("show_stocks <", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksLessThanOrEqualTo(Integer value) {
            addCriterion("show_stocks <=", value, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksIn(List<Integer> values) {
            addCriterion("show_stocks in", values, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksNotIn(List<Integer> values) {
            addCriterion("show_stocks not in", values, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksBetween(Integer value1, Integer value2) {
            addCriterion("show_stocks between", value1, value2, "showStocks");
            return (Criteria) this;
        }

        public Criteria andShowStocksNotBetween(Integer value1, Integer value2) {
            addCriterion("show_stocks not between", value1, value2, "showStocks");
            return (Criteria) this;
        }

        public Criteria andWishTitleIsNull() {
            addCriterion("wish_title is null");
            return (Criteria) this;
        }

        public Criteria andWishTitleIsNotNull() {
            addCriterion("wish_title is not null");
            return (Criteria) this;
        }

        public Criteria andWishTitleEqualTo(String value) {
            addCriterion("wish_title =", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleNotEqualTo(String value) {
            addCriterion("wish_title <>", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleGreaterThan(String value) {
            addCriterion("wish_title >", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleGreaterThanOrEqualTo(String value) {
            addCriterion("wish_title >=", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleLessThan(String value) {
            addCriterion("wish_title <", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleLessThanOrEqualTo(String value) {
            addCriterion("wish_title <=", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleLike(String value) {
            addCriterion("wish_title like", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleNotLike(String value) {
            addCriterion("wish_title not like", value, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleIn(List<String> values) {
            addCriterion("wish_title in", values, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleNotIn(List<String> values) {
            addCriterion("wish_title not in", values, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleBetween(String value1, String value2) {
            addCriterion("wish_title between", value1, value2, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishTitleNotBetween(String value1, String value2) {
            addCriterion("wish_title not between", value1, value2, "wishTitle");
            return (Criteria) this;
        }

        public Criteria andWishNumberIsNull() {
            addCriterion("wish_number is null");
            return (Criteria) this;
        }

        public Criteria andWishNumberIsNotNull() {
            addCriterion("wish_number is not null");
            return (Criteria) this;
        }

        public Criteria andWishNumberEqualTo(Integer value) {
            addCriterion("wish_number =", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberNotEqualTo(Integer value) {
            addCriterion("wish_number <>", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberGreaterThan(Integer value) {
            addCriterion("wish_number >", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("wish_number >=", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberLessThan(Integer value) {
            addCriterion("wish_number <", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberLessThanOrEqualTo(Integer value) {
            addCriterion("wish_number <=", value, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberIn(List<Integer> values) {
            addCriterion("wish_number in", values, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberNotIn(List<Integer> values) {
            addCriterion("wish_number not in", values, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberBetween(Integer value1, Integer value2) {
            addCriterion("wish_number between", value1, value2, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andWishNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("wish_number not between", value1, value2, "wishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberIsNull() {
            addCriterion("real_wish_number is null");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberIsNotNull() {
            addCriterion("real_wish_number is not null");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberEqualTo(Integer value) {
            addCriterion("real_wish_number =", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberNotEqualTo(Integer value) {
            addCriterion("real_wish_number <>", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberGreaterThan(Integer value) {
            addCriterion("real_wish_number >", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("real_wish_number >=", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberLessThan(Integer value) {
            addCriterion("real_wish_number <", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberLessThanOrEqualTo(Integer value) {
            addCriterion("real_wish_number <=", value, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberIn(List<Integer> values) {
            addCriterion("real_wish_number in", values, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberNotIn(List<Integer> values) {
            addCriterion("real_wish_number not in", values, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberBetween(Integer value1, Integer value2) {
            addCriterion("real_wish_number between", value1, value2, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andRealWishNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("real_wish_number not between", value1, value2, "realWishNumber");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitIsNull() {
            addCriterion("is_stock_split is null");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitIsNotNull() {
            addCriterion("is_stock_split is not null");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitEqualTo(Boolean value) {
            addCriterion("is_stock_split =", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitNotEqualTo(Boolean value) {
            addCriterion("is_stock_split <>", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitGreaterThan(Boolean value) {
            addCriterion("is_stock_split >", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_stock_split >=", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitLessThan(Boolean value) {
            addCriterion("is_stock_split <", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitLessThanOrEqualTo(Boolean value) {
            addCriterion("is_stock_split <=", value, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitIn(List<Boolean> values) {
            addCriterion("is_stock_split in", values, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitNotIn(List<Boolean> values) {
            addCriterion("is_stock_split not in", values, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitBetween(Boolean value1, Boolean value2) {
            addCriterion("is_stock_split between", value1, value2, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andIsStockSplitNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_stock_split not between", value1, value2, "isStockSplit");
            return (Criteria) this;
        }

        public Criteria andUsingTitleIsNull() {
            addCriterion("using_title is null");
            return (Criteria) this;
        }

        public Criteria andUsingTitleIsNotNull() {
            addCriterion("using_title is not null");
            return (Criteria) this;
        }

        public Criteria andUsingTitleEqualTo(Boolean value) {
            addCriterion("using_title =", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleNotEqualTo(Boolean value) {
            addCriterion("using_title <>", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleGreaterThan(Boolean value) {
            addCriterion("using_title >", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("using_title >=", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleLessThan(Boolean value) {
            addCriterion("using_title <", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleLessThanOrEqualTo(Boolean value) {
            addCriterion("using_title <=", value, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleIn(List<Boolean> values) {
            addCriterion("using_title in", values, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleNotIn(List<Boolean> values) {
            addCriterion("using_title not in", values, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleBetween(Boolean value1, Boolean value2) {
            addCriterion("using_title between", value1, value2, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andUsingTitleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("using_title not between", value1, value2, "usingTitle");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private jumei_deals_pluginExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(jumei_deals_pluginExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public jumei_deals_pluginExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table jumei_deals_plugin
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void criteria(Criteria criteria);
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table jumei_deals_plugin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_deals_plugin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void example(model.tuanmei_operation.pojo.jumei_deals_pluginExample example);
    }
}