package model.jumei_product.dao;

import java.util.List;
import model.jumei_product.pojo.jumei_tag;
import model.jumei_product.pojo.jumei_tagExample;
import org.apache.ibatis.annotations.Param;

public interface jumei_tagMapper {
    long countByExample(jumei_tagExample example);

    int deleteByExample(jumei_tagExample example);

    int deleteByPrimaryKey(Integer tagId);

    int insert(jumei_tag record);

    int insertSelective(jumei_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    jumei_tag selectOneByExample(jumei_tagExample example);

    List<jumei_tag> selectByExample(jumei_tagExample example);

    jumei_tag selectByPrimaryKey(Integer tagId);

    int updateByExampleSelective(@Param("record") jumei_tag record, @Param("example") jumei_tagExample example);

    int updateByExample(@Param("record") jumei_tag record, @Param("example") jumei_tagExample example);

    int updateByPrimaryKeySelective(jumei_tag record);

    int updateByPrimaryKey(jumei_tag record);
}