package model.jumei_product.dao;

import java.util.List;
import model.jumei_product.pojo.tuanmei_deals;
import model.jumei_product.pojo.tuanmei_dealsExample;
import org.apache.ibatis.annotations.Param;

public interface tuanmei_dealsMapper {
    long countByExample(tuanmei_dealsExample example);

    int deleteByExample(tuanmei_dealsExample example);

    int deleteByPrimaryKey(Integer dealId);

    int insert(tuanmei_deals record);

    int insertSelective(tuanmei_deals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuanmei_deals
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    tuanmei_deals selectOneByExample(tuanmei_dealsExample example);

    List<tuanmei_deals> selectByExample(tuanmei_dealsExample example);

    tuanmei_deals selectByPrimaryKey(Integer dealId);

    int updateByExampleSelective(@Param("record") tuanmei_deals record, @Param("example") tuanmei_dealsExample example);

    int updateByExample(@Param("record") tuanmei_deals record, @Param("example") tuanmei_dealsExample example);

    int updateByPrimaryKeySelective(tuanmei_deals record);

    int updateByPrimaryKey(tuanmei_deals record);
}