package model.jumei_product.dao;

import java.util.List;
import model.jumei_product.pojo.tuanmei_product_inventory;
import model.jumei_product.pojo.tuanmei_product_inventoryExample;
import org.apache.ibatis.annotations.Param;

public interface tuanmei_product_inventoryMapper {
    long countByExample(tuanmei_product_inventoryExample example);

    int deleteByExample(tuanmei_product_inventoryExample example);

    int deleteByPrimaryKey(String skuNo);

    int insert(tuanmei_product_inventory record);

    int insertSelective(tuanmei_product_inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuanmei_product_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    tuanmei_product_inventory selectOneByExample(tuanmei_product_inventoryExample example);

    List<tuanmei_product_inventory> selectByExample(tuanmei_product_inventoryExample example);

    tuanmei_product_inventory selectByPrimaryKey(String skuNo);

    int updateByExampleSelective(@Param("record") tuanmei_product_inventory record, @Param("example") tuanmei_product_inventoryExample example);

    int updateByExample(@Param("record") tuanmei_product_inventory record, @Param("example") tuanmei_product_inventoryExample example);

    int updateByPrimaryKeySelective(tuanmei_product_inventory record);

    int updateByPrimaryKey(tuanmei_product_inventory record);
}