package model.tuanmei_operation.dao;

import java.util.List;
import model.tuanmei_operation.pojo.jumei_mall_draft;
import model.tuanmei_operation.pojo.jumei_mall_draftExample;
import org.apache.ibatis.annotations.Param;

public interface jumei_mall_draftMapper {
    long countByExample(jumei_mall_draftExample example);

    int deleteByExample(jumei_mall_draftExample example);

    int deleteByPrimaryKey(Integer mallId);

    int insert(jumei_mall_draft record);

    int insertSelective(jumei_mall_draft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_mall_draft
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    jumei_mall_draft selectOneByExample(jumei_mall_draftExample example);

    List<jumei_mall_draft> selectByExample(jumei_mall_draftExample example);

    jumei_mall_draft selectByPrimaryKey(Integer mallId);

    int updateByExampleSelective(@Param("record") jumei_mall_draft record, @Param("example") jumei_mall_draftExample example);

    int updateByExample(@Param("record") jumei_mall_draft record, @Param("example") jumei_mall_draftExample example);

    int updateByPrimaryKeySelective(jumei_mall_draft record);

    int updateByPrimaryKey(jumei_mall_draft record);
}