package model.tuanmei_operation.dao;

import java.util.List;
import model.tuanmei_operation.pojo.tuanmei_deal_drafts;
import model.tuanmei_operation.pojo.tuanmei_deal_draftsExample;
import model.tuanmei_operation.pojo.tuanmei_deal_draftsWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface tuanmei_deal_draftsMapper {
    long countByExample(tuanmei_deal_draftsExample example);

    int deleteByExample(tuanmei_deal_draftsExample example);

    int deleteByPrimaryKey(String hashId);

    int insert(tuanmei_deal_draftsWithBLOBs record);

    int insertSelective(tuanmei_deal_draftsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuanmei_deal_drafts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    tuanmei_deal_drafts selectOneByExample(tuanmei_deal_draftsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuanmei_deal_drafts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    tuanmei_deal_draftsWithBLOBs selectOneByExampleWithBLOBs(tuanmei_deal_draftsExample example);

    List<tuanmei_deal_draftsWithBLOBs> selectByExampleWithBLOBs(tuanmei_deal_draftsExample example);

    List<tuanmei_deal_drafts> selectByExample(tuanmei_deal_draftsExample example);

    tuanmei_deal_draftsWithBLOBs selectByPrimaryKey(String hashId);

    int updateByExampleSelective(@Param("record") tuanmei_deal_draftsWithBLOBs record, @Param("example") tuanmei_deal_draftsExample example);

    int updateByExampleWithBLOBs(@Param("record") tuanmei_deal_draftsWithBLOBs record, @Param("example") tuanmei_deal_draftsExample example);

    int updateByExample(@Param("record") tuanmei_deal_drafts record, @Param("example") tuanmei_deal_draftsExample example);

    int updateByPrimaryKeySelective(tuanmei_deal_draftsWithBLOBs record);

    int updateByPrimaryKeyWithBLOBs(tuanmei_deal_draftsWithBLOBs record);

    int updateByPrimaryKey(tuanmei_deal_drafts record);
}