package model.jumei_product.pojo;

import java.util.Date;

public class jumei_tag {
    private Integer tagId;

    private String tagName;

    private Byte tagStatus;

    private String tagDescription;

    private Date lastUpdateTime;

    private String lastUpdateUser;

    private String tagSaleImg;

    private String tagUseType;

    public jumei_tag(Integer tagId, String tagName, Byte tagStatus, String tagDescription, Date lastUpdateTime, String lastUpdateUser, String tagSaleImg, String tagUseType) {
        this.tagId = tagId;
        this.tagName = tagName;
        this.tagStatus = tagStatus;
        this.tagDescription = tagDescription;
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateUser = lastUpdateUser;
        this.tagSaleImg = tagSaleImg;
        this.tagUseType = tagUseType;
    }

    public jumei_tag() {
        super();
    }

    public Integer getTagId() {
        return tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    public String getTagName() {
        return tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    public Byte getTagStatus() {
        return tagStatus;
    }

    public void setTagStatus(Byte tagStatus) {
        this.tagStatus = tagStatus;
    }

    public String getTagDescription() {
        return tagDescription;
    }

    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription == null ? null : tagDescription.trim();
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    public String getTagSaleImg() {
        return tagSaleImg;
    }

    public void setTagSaleImg(String tagSaleImg) {
        this.tagSaleImg = tagSaleImg == null ? null : tagSaleImg.trim();
    }

    public String getTagUseType() {
        return tagUseType;
    }

    public void setTagUseType(String tagUseType) {
        this.tagUseType = tagUseType == null ? null : tagUseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumei_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static jumei_tag.Builder builder() {
        return new jumei_tag.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jumei_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jumei_tag
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private jumei_tag obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_tag
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new jumei_tag();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_id
         *
         * @param tagId the value for jumei_tag.tag_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagId(Integer tagId) {
            obj.setTagId(tagId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_name
         *
         * @param tagName the value for jumei_tag.tag_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagName(String tagName) {
            obj.setTagName(tagName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_status
         *
         * @param tagStatus the value for jumei_tag.tag_status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagStatus(Byte tagStatus) {
            obj.setTagStatus(tagStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_description
         *
         * @param tagDescription the value for jumei_tag.tag_description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagDescription(String tagDescription) {
            obj.setTagDescription(tagDescription);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.last_update_time
         *
         * @param lastUpdateTime the value for jumei_tag.last_update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lastUpdateTime(Date lastUpdateTime) {
            obj.setLastUpdateTime(lastUpdateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.last_update_user
         *
         * @param lastUpdateUser the value for jumei_tag.last_update_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lastUpdateUser(String lastUpdateUser) {
            obj.setLastUpdateUser(lastUpdateUser);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_sale_img
         *
         * @param tagSaleImg the value for jumei_tag.tag_sale_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagSaleImg(String tagSaleImg) {
            obj.setTagSaleImg(tagSaleImg);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column jumei_tag.tag_use_type
         *
         * @param tagUseType the value for jumei_tag.tag_use_type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tagUseType(String tagUseType) {
            obj.setTagUseType(tagUseType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jumei_tag
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public jumei_tag build() {
            return this.obj;
        }
    }
}